### ISSUE TITLE
Create reactive variable without initial value

### ISSUE THREAD

**Issue by vasarhelyia** [bvic23/VinceRP#16]
Currently, it's not possible and it would be great to just specify the type of the future values pushed into a given `reactive()` variable. Workaround is to initialize it with an empty value, like `""` in case of String, or an extreme value to filter for in the observer side.

**Comment by bvic23** [comment]
https://github.com/bvic23/VinceRP/commit/ef653b8f31ba21092f4489c6e2f5a2fd6e3f89ca
